name: Golden Retriever example
description: This is golden retriever example of running hono server with postgres db

useDocker: true

required:
  bun:
    why:
      - For running hono server in goldern-example
    install:
      - curl -fsSL https://bun.sh/install | bash
    checkCmd: bun -v

db_services:
  golden-retriever-example-db:
    driver: postgres
    databaseName: golden
    user: user
    password: password
    port: 5689
  golden-retriever-example-redis:
    driver: redis-server
    user: user
    port: 6399

services:
  golder-example:
    port: 3000
    path: .
    depends_on_db:
      - name: golden-retriever-example-db
        envAlias: none
      - name: golden-retriever-example-redis
        envAlias: none
    depends_on_services:
      - name: golder-example
        envAlias: baseUrl
        suffix: /api
    beforeStart:
      - bun install
    start:
      - bun dev
      - sleep 10 && open http://localhost:3000/docs
      - sleep 10 && open http://localhost:3000/graphql

  golde-example-website:
    port: 3005
    cloneFrom: https://github.com/Andriiklymiuk/golden-example-website.git
    environment:
      - NEXT_PUBLIC_API_KEY=your-api-key-here
    depends_on_services:
      - name: golder-example
        envAlias: NEXT_PUBLIC_BACKEND_URL
    beforeStart:
      - bun install
    start:
      - bun dev
      - sleep 10 && open http://localhost:3005
